version: '3'

services:
    powershell:
        container_name: powershell
        build:
            context: ./
            dockerfile: ./powershell/Dockerfile
        ports:
            - "52:22"
        networks:
            - powershell
        tty: true
        privileged: true

            
networks:
    powershell:
        driver: bridge
